source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/duanLss/moduleSpecs.git'

use_frameworks!
platform :ios, '12.0'

target 'DHPaddleLiteSDK_Example' do
  
  pod 'DLVideoCapture'
  pod 'PaddleLiteiOS', :path => '../../PaddleLiteiOS'
  pod 'DHPaddleLiteSDK/PhoneNumberRecognizer', :path => '../'
  pod 'DHPaddleLiteSDK/OCRModelV4', :path => '../'

  target 'DHPaddleLiteSDK_Tests' do
    inherit! :search_paths
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
